language: php
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: change

branches:
  only:
    - master

matrix:
  include:
    - php: 5.3
      env: WP_VERSION=latest
      dist: precise
    - php: 5.6
      env: WP_VERSION=4.4
    - php: 5.6
      env: WP_VERSION=latest
    - php: 5.6
      env: WP_VERSION=nightly
    - php: 7
      env: WP_VERSION=latest

before_script:
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [[ ${TRAVIS_PHP_VERSION:0:3} == "7.0" ]]; then
      composer global require "phpunit/phpunit=5.6.*"
    else
      composer global require "phpunit/phpunit=4.8.*"
    fi
  - |
    composer global require wp-coding-standards/wpcs
    phpcs --config-set installed_paths $HOME/.composer/vendor/wp-coding-standards/wpcs

script:
  - phpcs
  - phpunit
  - phpunit -c multisite.xml.dist
