version: 2
jobs:
  build:
    working_directory: ~/pantheon-systems/pantheon-advanced-page-cache
    parallelism: 1
    shell: /bin/bash --login
    docker:
    - image: circleci/php:7.1.18-apache-node-browsers
      command: /sbin/init
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dep-{{ .Branch }}-
        - v1-dep-master-
    - run: echo $(openssl rand -hex 8) > ~/WORDPRESS_ADMIN_PASSWORD
    - run: echo "date.timezone = 'US/Central'"  >  /opt/circleci/php/7.0.7/etc/conf.d/xdebug.ini
    - run: |
        echo 'export PATH=~/terminus/bin:$PATH' >> $BASH_ENV
        echo 'export TERMINUS_ENV=ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export TERMINUS_SITE=pantheon-advanced-page-cache' >> $BASH_ENV
        echo 'export SITE_ENV=pantheon-advanced-page-cache.ci-$CIRCLE_BUILD_NUM' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_USERNAME=pantheon' >> $BASH_ENV
        echo 'export WORDPRESS_ADMIN_PASSWORD=$(cat ~/WORDPRESS_ADMIN_PASSWORD)' >> $BASH_ENV
        source $BASH_ENV
    - run: |
        if [ -z "$GITHUB_TOKEN" ]; then
          echo "GITHUB_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        echo "Setting GitHub OAuth token with suppressed ouput"
        {
          composer config -g github-oauth.github.com $GITHUB_TOKEN
        } &> /dev/null
    - run: |
        if [ -z "$TERMINUS_TOKEN" ]; then
          echo "TERMINUS_TOKEN environment variables missing; assuming unauthenticated build"
          exit 0
        fi
        composer install
        git clone --branch master https://github.com/pantheon-systems/terminus.git ~/terminus
        cd ~/terminus && composer install
        terminus auth:login --machine-token=$TERMINUS_TOKEN
    - save_cache:
        key: v1-dep-{{ .Branch }}-{{ epoch }}
        paths:
        - ~/.composer/cache
        - ./node_modules
    - run: ./bin/behat-prepare.sh
    - run: ./bin/behat-test.sh
    - run: ./bin/behat-cleanup.sh
